/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentation;

import DAO.DBConnection;
import DAO.UserDAO;
import Model.Employee;
import Model.User;
import Service.EmployeeService;
import Service.UserService;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CpELaboratory 216
 */
public class AddRecordDialog extends javax.swing.JDialog {
    
    private static final EmployeeService service = new EmployeeService();
    /**
     * Creates new form EmployeeRecordDialog
     */
    
    public AddRecordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateRolesDropdown();
        setTitle("Add Employee Record");       
    }
    
    private void populateRolesDropdown() {
        roleCmb.removeAllItems(); // Clear any design-time placeholders
    
        try {
            // Fetch the list from the DAO package
            DAO.EmployeeDAO dao = new DAO.EmployeeDAO();
            java.util.List<String> roles = dao.getRoleNames();
        
            for (String role : roles) {
                roleCmb.addItem(role);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Could not load database roles into UI: " + e.getMessage(), 
                "Database Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        
        // Hardcoded safe fallbacks if the database drops during runtime
            roleCmb.addItem("Standard_Employee");
            roleCmb.addItem("HR_Admin");
        }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        departmentTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roleCmb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        contactNumTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogPanel.setBackground(new java.awt.Color(51, 51, 51));

        addBtn.setBackground(new java.awt.Color(0, 102, 255));
        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        nameTxt.setForeground(new java.awt.Color(0, 0, 0));
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("[ Name: ]");

        departmentTxt.setForeground(new java.awt.Color(0, 0, 0));
        departmentTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departmentTxtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("[ Department: ]");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("[ Email ]");

        emailTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("[ Salary ]");

        salaryTxt.setForeground(new java.awt.Color(0, 0, 0));
        salaryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTxtKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("[ Role: ]");

        roleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("[ Contact Number ]");

        contactNumTxt.setForeground(new java.awt.Color(0, 0, 0));
        contactNumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNumTxtKeyTyped(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Add Employee");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("[ Address: ]");

        addressTxt.setForeground(new java.awt.Color(0, 0, 0));
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout dialogPanelLayout = new javax.swing.GroupLayout(dialogPanel);
        dialogPanel.setLayout(dialogPanelLayout);
        dialogPanelLayout.setHorizontalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPanelLayout.createSequentialGroup()
                                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dialogPanelLayout.createSequentialGroup()
                                        .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(dialogPanelLayout.createSequentialGroup()
                                                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                                        .addComponent(departmentTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(salaryTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(contactNumTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(jLabel2))
                                                .addGap(39, 39, 39)
                                                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5))))
                                        .addGap(36, 36, 36))
                                    .addComponent(cancelBtn)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(124, 124, 124)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addComponent(addBtn)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPanelLayout.createSequentialGroup()
                                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))
                    .addGroup(dialogPanelLayout.createSequentialGroup()
                        .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        dialogPanelLayout.setVerticalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(addBtn))
                .addGap(60, 60, 60))
        );

        getContentPane().add(dialogPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // 1. Extract and clean values from your form components
        String name = nameTxt.getText().trim();
        String address = addressTxt.getText().trim();
        String department = departmentTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String contactNum = contactNumTxt.getText().trim();
        String selectedRole = roleCmb.getSelectedItem().toString();

        double salary = 0.0;
        try {
            salary = Double.parseDouble(salaryTxt.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid decimal number for Salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate inputs before running database operations
        if (name.isEmpty() || department.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, Department, and Email fields cannot be blank.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

       
        try {
           
            
            UserService uServ =  new UserService();    
            User savedUser = uServ.registerUserAccount(email, selectedRole);

            // Form the matching HR Profile mapping
            Employee emp = new Employee();
            emp.setUser(savedUser); // Links the database auto-incremented user ID!
            emp.setName(name);
            emp.setAddress(address);
            emp.setContactNum(contactNum);
            emp.setDepartment(department);
            emp.setSalary(salary);
            emp.setStatus("Active");
            emp.setDateHired(java.time.LocalDate.now());

            // Save details to the employee table using your EmployeeService
            boolean isProfileSaved = service.registerEmployee(emp);

            if (isProfileSaved) {
                // Success! Display the temporary credentials to the administrator
              JOptionPane.showMessageDialog(this, 
               "Account Successfully Created!\n\n" +
               "Give these credentials to the employee:\n" +
                    "Username/Email: " + savedUser.getEmail() + "\n" +
                   "Temporary Password: " + savedUser.getTemporaryPassword(),
                 "Registration Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear text fields
                nameTxt.setText("");
                addressTxt.setText("");
                departmentTxt.setText("");
                emailTxt.setText("");
                salaryTxt.setText("");
                contactNumTxt.setText("");

                // Refresh visual display table
                EmployeePanel employee = new EmployeePanel();
                if(employee != null){
                employee.loadTable();
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "User credentials created, but failed to initialize HR profile.", 
                        "Data Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database entry failed: " + ex.getMessage(), 
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
    }//GEN-LAST:event_addBtnActionPerformed

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        
    String fullName = nameTxt.getText().trim();

    if (!fullName.isEmpty()) {

      UserDAO userDAO = new UserDAO();

      // Generate the unique email dynamically as they type!

      String uniqueEmail = userDAO.generateUniqueEmail(fullName);

      emailTxt.setText(uniqueEmail); // Display it on-the-fly in a non-editable field

    } else {

      emailTxt.setText("");

    }
    }//GEN-LAST:event_nameTxtKeyReleased

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
        char c = evt.getKeyChar();
    
        // Allow letters, spaces, hyphens, and apostrophes only
        if (!Character.isLetter(c) && c != ' ' && c != '-' && c != '\'') {
            evt.consume(); // Ignore the keystroke
        }
    }//GEN-LAST:event_nameTxtKeyTyped

    private void departmentTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departmentTxtKeyTyped
        char c = evt.getKeyChar();
    
    // Allow letters, spaces, hyphens, and apostrophes only
        if (!Character.isLetter(c) && c != ' ' && c != '-' && c != '\'') {
        evt.consume(); // Ignore the keystroke
        }
    }//GEN-LAST:event_departmentTxtKeyTyped

    private void salaryTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTxtKeyTyped
        char c = evt.getKeyChar();
    
        // Allow only digits and a dot
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Reject letter keys
        }
    
        // Prevent typing a second decimal point if one already exists
        if (c == '.' && salaryTxt.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_salaryTxtKeyTyped

    private void contactNumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumTxtKeyTyped
        char c = evt.getKeyChar();
    
        // Allow only digits and a '+' symbol at the start
        if (!Character.isDigit(c) && c != '+') {
            evt.consume(); // Reject letter keys
        }
    
        // Block '+' if it's not the very first character
        if (c == '+' && contactNumTxt.getText().length() > 0) {
            evt.consume(); 
        }
    }//GEN-LAST:event_contactNumTxtKeyTyped

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtKeyReleased

    private void addressTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddRecordDialog dialog = new AddRecordDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField contactNumTxt;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JPanel dialogPanel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> roleCmb;
    private javax.swing.JTextField salaryTxt;
    // End of variables declaration//GEN-END:variables
}
