/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentation;

import DAO.DBConnection;
import Model.Employee;
import Model.User;
import Service.EmployeeService;
import Service.UserService;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CpELaboratory 216
 */
public class EmployeeRecordDialog extends javax.swing.JDialog {
    
    private static final EmployeeService service = new EmployeeService();
    /**
     * Creates new form EmployeeRecordDialog
     */
    
    public EmployeeRecordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateRolesDropdown();
        setTitle("Add Dialog");       
    }
    
    private void populateRolesDropdown() {
    roleCmb.removeAllItems(); // Clear default placeholders
    
    // Explicitly query your database roles metadata
    String sql = "SELECT `name` FROM `roles`";
    try (
        Connection conn = DBConnection.GetConnection();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery()
    ) {
        while (rs.next()) {
            roleCmb.addItem(rs.getString("name"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,"Could not load database roles into UI: " + e.getMessage());
        // Fallback options in case database connection fails during startup
        roleCmb.addItem("Standard_Employee");
        roleCmb.addItem("HR_Admin");
    }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        departmentTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roleCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dialogPanel.setBackground(new java.awt.Color(51, 51, 51));

        addBtn.setBackground(new java.awt.Color(51, 255, 51));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("[ Name: ]");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("[ Department: ]");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("[ Email ]");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("[ Salary ]");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("[ Role: ]");

        roleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout dialogPanelLayout = new javax.swing.GroupLayout(dialogPanel);
        dialogPanel.setLayout(dialogPanelLayout);
        dialogPanelLayout.setHorizontalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTxt)
                    .addComponent(departmentTxt)
                    .addGroup(dialogPanelLayout.createSequentialGroup()
                        .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(addBtn))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addComponent(emailTxt)
                    .addComponent(salaryTxt))
                .addGap(18, 18, 18)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        dialogPanelLayout.setVerticalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addBtn)
                .addGap(14, 14, 14)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(dialogPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // 1. Extract and clean values from your form components
        String name = nameTxt.getText().trim();
        String department = departmentTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String selectedRole = roleCmb.getSelectedItem().toString();

        double salary = 0.0;
        try {
            salary = Double.parseDouble(salaryTxt.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid decimal number for Salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Validate inputs before running database operations
        if (name.isEmpty() || department.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, Department, and Email fields cannot be blank.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Wrap in a try-catch to satisfy compilation and catch SQL errors safely
        try {
           
            // Step A: Register security credentials and capture the generated password/ID
            UserService uServ =  new UserService();    
            User savedUser = uServ.registerUserAccount(email, selectedRole);

            // Step B: Form the matching HR Profile mapping
            Employee emp = new Employee();
            emp.setUser(savedUser); // Links the database auto-incremented user ID!
            emp.setName(name);
            emp.setDepartment(department);
            emp.setSalary(salary);
            emp.setStatus("Active");
            emp.setDateHired(java.time.LocalDate.now());

            // Step C: Save details to the employee table using your EmployeeService
            boolean isProfileSaved = service.registerEmployee(emp);

            if (isProfileSaved) {
                // Success! Display the temporary credentials to the administrator
              JOptionPane.showMessageDialog(this, 
               "Account Successfully Created!\n\n" +
               "Give these credentials to the employee:\n" +
                    "Username/Email: " + savedUser.getEmail() + "\n" +
                   "Temporary Password: " + savedUser.getTemporaryPassword(),
                 "Registration Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear text fields
                nameTxt.setText("");
                departmentTxt.setText("");
                emailTxt.setText("");
                salaryTxt.setText("");

                // Refresh visual display table
                EmployeePanel employee = new EmployeePanel();
                
                employee.loadTable();
            } else {
                JOptionPane.showMessageDialog(this, "User credentials created, but failed to initialize HR profile.", 
                        "Data Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database entry failed: " + ex.getMessage(), 
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeRecordDialog dialog = new EmployeeRecordDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JPanel dialogPanel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> roleCmb;
    private javax.swing.JTextField salaryTxt;
    // End of variables declaration//GEN-END:variables
}
