package Presentation;


import Model.Role;
import Presentation.EmployeePanel;
import Presentation.EvaluationPanel;
import Presentation.HomePanel2;
import Presentation.HomePanel2;
import Presentation.MainFrame;
import Presentation.MainFrame;
import Presentation.RequestPanel;
import Presentation.RequestPanel;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Window;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author BE214
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    private Role role;
    
    public HomePanel() {
        
        initComponents();
        mainPanel.removeAll();
        mainPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(new HomePanel2(), java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public HomePanel(Role role){
        this();
        this.role = role;
        
        if ("Standard_Employee".equals(role.getRoleName())) {
            employeeBtn.setEnabled(false);
            evaluationBtn.setEnabled(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        extraPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        evaluationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.BorderLayout());

        extraPanel.setBackground(new java.awt.Color(102, 102, 102));
        extraPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(extraPanel, java.awt.BorderLayout.LINE_START);

        sidePanel.setBackground(new java.awt.Color(17, 24, 39));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sidePanel.setToolTipText("");
        sidePanel.setPreferredSize(new java.awt.Dimension(250, 400));

        jPanel1.setBackground(new java.awt.Color(17, 24, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        employeeBtn.setBackground(new java.awt.Color(17, 24, 39));
        employeeBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        employeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/users_icon.png"))); // NOI18N
        employeeBtn.setText("Employee Records");
        employeeBtn.setActionCommand("            Employee Records");
        employeeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 51, 56), 0, true));
        employeeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeBtn.setPreferredSize(new java.awt.Dimension(65, 22));
        employeeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeBtnMouseClicked(evt);
            }
        });
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(17, 24, 39));
        homeBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_icon (1).png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setActionCommand("      Home");
        homeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 51, 56), 0, true));
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeBtn.setMaximumSize(new java.awt.Dimension(172, 22));
        homeBtn.setMinimumSize(new java.awt.Dimension(172, 22));
        homeBtn.setPreferredSize(new java.awt.Dimension(90, 22));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        requestBtn.setBackground(new java.awt.Color(17, 24, 39));
        requestBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        requestBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/document_icon.png"))); // NOI18N
        requestBtn.setText("Request");
        requestBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 51, 56), 0, true));
        requestBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        requestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestBtnMouseClicked(evt);
            }
        });
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(17, 24, 39));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout_icon.png"))); // NOI18N
        logOutBtn.setText("Logout");
        logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 51, 56), 0, true));
        logOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logOutBtn.setPreferredSize(new java.awt.Dimension(72, 22));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(17, 24, 39));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Screenshot 2026-07-16 064719.png"))); // NOI18N

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("CREWDECK");

        evaluationBtn.setBackground(new java.awt.Color(17, 24, 39));
        evaluationBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        evaluationBtn.setForeground(new java.awt.Color(255, 255, 255));
        evaluationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/star_icon.png"))); // NOI18N
        evaluationBtn.setText("Evalution");
        evaluationBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 51, 56), 0, true));
        evaluationBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        evaluationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluationBtnMouseClicked(evt);
            }
        });
        evaluationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(evaluationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        EmployeePanel panel2 = new EmployeePanel();

        mainPanel.removeAll();
        mainPanel.add(panel2);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        RequestPanel panel = new RequestPanel();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_requestBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePanel2 panel = new HomePanel2();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        homeBtn.setBackground(Color.DARK_GRAY);
   
        evaluationBtn.setBackground(Color.BLACK);
        
        employeeBtn.setBackground(Color.BLACK); 
        requestBtn.setBackground(Color.BLACK);


    }//GEN-LAST:event_homeBtnMouseClicked

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        MainFrame panel = new MainFrame();
        
        
        logOutBtn.setBackground(Color.DARK_GRAY);
        
        evaluationBtn.setBackground(Color.BLACK);       
        employeeBtn.setBackground(Color.BLACK); 
        requestBtn.setBackground(Color.BLACK);
        homeBtn.setBackground(Color.BLACK); 
        
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout", JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            
            // Used for closing the HomePanel
            Window hpanel = SwingUtilities.getWindowAncestor(this);           
        
            if (hpanel != null) {
            
                hpanel.dispose(); // Close the current window completely            
                panel.setVisible(true); // Open a fresh MainFrame (showing the login screen)
              
            }
         
    }
        
        

        
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void employeeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeBtnMouseClicked
        employeeBtn.setBackground(Color.DARK_GRAY);
   
        evaluationBtn.setBackground(Color.BLACK);        
        homeBtn.setBackground(Color.BLACK); 
        requestBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_employeeBtnMouseClicked

    private void requestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestBtnMouseClicked
        requestBtn.setBackground(Color.DARK_GRAY);  
        evaluationBtn.setBackground(Color.BLACK);    
        employeeBtn.setBackground(Color.BLACK); 
        homeBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_requestBtnMouseClicked

    private void evaluationBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationBtnMouseClicked
        evaluationBtn.setBackground(Color.DARK_GRAY);
   
        homeBtn.setBackground(Color.BLACK);        
        employeeBtn.setBackground(Color.BLACK); 
        requestBtn.setBackground(Color.BLACK);
        
        
    
    }//GEN-LAST:event_evaluationBtnMouseClicked

    private void evaluationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationBtnActionPerformed
        EvaluationPanel panel = new EvaluationPanel();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_evaluationBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton evaluationBtn;
    private javax.swing.JPanel extraPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton requestBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    
}
