package Presentation;

import Model.Role;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Connection;
import DAO.DBConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class MainFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        setTitle("CrewDeck");
        initComponents();
        setSize(1091, 642);
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(49, 51, 56));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(56, 58, 64));
        loginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        loginPanel.setMaximumSize(new java.awt.Dimension(500, 500));
        loginPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        loginPanel.setName(""); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(350, 360));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("CREWDECK");
        loginPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 68, 200, 100));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 238, -1, -1));

        Username.setBackground(new java.awt.Color(30, 31, 34));
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 80, 88)));
        Username.setPreferredSize(new java.awt.Dimension(65, 18));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        loginPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 258, 310, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 328, -1, -1));

        Password.setBackground(new java.awt.Color(30, 31, 34));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(78, 80, 88)));
        Password.setPreferredSize(new java.awt.Dimension(61, 18));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        loginPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 348, 310, 40));

        loginButton.setBackground(new java.awt.Color(88, 101, 242));
        loginButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(65, 25));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 428, 314, 45));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Management System");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 148, -1, -1));

        MainPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 485, 520));

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String correctpass = "12345678";
        String correctuser = "   Admin";
        String correctId1 = "1";
        String correctId2 = "2";
        String correctPass1 = "123";
        String correctPass2 = "1234";
        String username = Username.getText();
        char[] pass = Password.getPassword();

        if ((String.valueOf(username).equals(correctuser)) && (String.valueOf(pass).equals(correctpass))) {
            JOptionPane.showMessageDialog(null, "Welcome:" + username);

            HomePanel panel = new HomePanel();
            getContentPane().removeAll(); //removes the MainFrame
            getContentPane().add(panel); //adds the HomePanel
            getContentPane().revalidate();
            getContentPane().repaint();

        }

        else if ((String.valueOf(username).equals(correctId1)) && (String.valueOf(pass).equals(correctPass1))) {
            JOptionPane.showMessageDialog(null, "Welcome:" + username);
            
            Role newRole = new Role(Username.getText());
            
            String role = "SELECT `name` FROM `roles`";
            try (
                    Connection conn = DBConnection.GetConnection(); 
                    PreparedStatement stmt = conn.prepareStatement(role); 
                    ResultSet rs = stmt.executeQuery()) {
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Could not get Role" + e.getMessage());
                
            }
            
            HomePanel panel = new HomePanel(newRole);

            getContentPane().removeAll(); //removes the MainFrame
            getContentPane().add(panel); //adds the HomePanel
            getContentPane().revalidate();
            getContentPane().repaint();

        } 
        else {
            JOptionPane.showMessageDialog(null, "Incorrect credentials");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
