package Presentation;

import Model.Role;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Connection;
import DAO.DBConnection;
import Presentation.HomePanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class MainFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        setTitle("CrewDeck");
        initComponents();
        setSize(1160, 642);
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(245, 245, 245));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.BorderLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 231, 235), 1, true));
        loginPanel.setMaximumSize(new java.awt.Dimension(500, 500));
        loginPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        loginPanel.setName(""); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(370, 360));
        loginPanel.setLayout(null);

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        titleLabel.setText("CREWDECK");
        loginPanel.add(titleLabel);
        titleLabel.setBounds(90, 50, 150, 50);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 114, 128));
        jLabel2.setText("Employee Record System");
        loginPanel.add(jLabel2);
        jLabel2.setBounds(50, 100, 190, 19);

        Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Username.setPreferredSize(new java.awt.Dimension(65, 18));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        loginPanel.add(Username);
        Username.setBounds(50, 180, 290, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 24, 39));
        jLabel3.setText("Password");
        loginPanel.add(jLabel3);
        jLabel3.setBounds(50, 250, 69, 19);

        Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Password.setPreferredSize(new java.awt.Dimension(61, 18));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        loginPanel.add(Password);
        Password.setBounds(50, 270, 290, 40);

        loginButton.setBackground(new java.awt.Color(37, 99, 235));
        loginButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        loginButton.setPreferredSize(new java.awt.Dimension(65, 25));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(50, 350, 290, 45);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Screenshot 2026-07-14 154828.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        loginPanel.add(jLabel4);
        jLabel4.setBounds(40, 50, 50, 50);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 24, 39));
        jLabel6.setText("ID");
        loginPanel.add(jLabel6);
        jLabel6.setBounds(50, 160, 14, 19);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/742619597_26719342551075883_1456908827130861350_n.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        loginPanel.add(jLabel5);
        jLabel5.setBounds(0, 180, 360, 440);

        MainPanel.add(loginPanel, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Main background.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String correctpass = "12345678";
        String correctuser = "   Admin";
        String correctId1 = "1";
        String correctId2 = "2";
        String correctPass1 = "123";
        String correctPass2 = "1234";
        String username = Username.getText();
        char[] pass = Password.getPassword();

        if ((String.valueOf(username).equals(correctuser)) && (String.valueOf(pass).equals(correctpass))) {
            JOptionPane.showMessageDialog(null, "Welcome:" + username);

            HomePanel panel = new HomePanel();
            getContentPane().removeAll(); //removes the MainFrame
            getContentPane().add(panel); //adds the HomePanel
            getContentPane().revalidate();
            getContentPane().repaint();

        }

        else if ((String.valueOf(username).equals(correctId1)) && (String.valueOf(pass).equals(correctPass1))) {
            JOptionPane.showMessageDialog(null, "Welcome:" + username);

            Role newRole = new Role(Username.getText());

            String role = "SELECT `name` FROM `roles`";
            try (
                Connection conn = DBConnection.GetConnection();
                PreparedStatement stmt = conn.prepareStatement(role);
                ResultSet rs = stmt.executeQuery()) {

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Could not get Role" + e.getMessage());

            }

            HomePanel panel = new HomePanel(newRole);

            getContentPane().removeAll(); //removes the MainFrame
            getContentPane().add(panel); //adds the HomePanel
            getContentPane().revalidate();
            getContentPane().repaint();

        }
        else {
            JOptionPane.showMessageDialog(null, "Incorrect credentials");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
