/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentation;

import Model.EmployeeStatus;
import DAO.DBConnection;
import Model.Employee;
import Model.User;

import Service.EmployeeService;
import Service.UserService;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author Acer Ryzen 5
 */
public class UpdateRecordDialog extends javax.swing.JDialog {
    
    private Employee employeeToUpdate;
    private EmployeePanel parentPanel;
    private static final EmployeeService service = new EmployeeService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateRecordDialog.class.getName());
    

    /**
     * Creates new form UpdateRecordDialog
     */
    public UpdateRecordDialog(java.awt.Frame parent, boolean modal, Employee employee, EmployeePanel parentPanel) {
       super(parent, modal);
       this.parentPanel = parentPanel;
       // 1. Initialize NetBeans UI elements first
        initComponents(); 
    
        // 2. Setup dropdown list data
        populateRolesDropdown();
        setTitle("Update Dialog");
        
        statusCmb.setModel(new DefaultComboBoxModel(EmployeeStatus.values()));
    
        // 3. Bind the employee record and populate the form fields
        this.employeeToUpdate = employee;
        if (this.employeeToUpdate != null) {
        populateFormFields();
        }
    }
    
    
    
    private void populateFormFields() {
        // ID field stays read-only/uneditable 
        idTxt.setText(String.valueOf(employeeToUpdate.getUserId()));
        nameTxt.setText(employeeToUpdate.getName());
        departmentTxt.setText(employeeToUpdate.getDepartment());
        contactNumTxt.setText(employeeToUpdate.getContactNum() != null ? employeeToUpdate.getContactNum() : "");
        addressTxt.setText(employeeToUpdate.getAddress() != null ? employeeToUpdate.getAddress() : "");
        salaryTxt.setText(String.valueOf(employeeToUpdate.getSalary()));
        
        // Bind Employee Status safely
        if (employeeToUpdate.getStatus() != null) {
            try {
                // Converts "ACTIVE" or "ON_LEAVE" string from DB to Enum constant
                EmployeeStatus currentStatus = Model.EmployeeStatus.valueOf(employeeToUpdate.getStatus().toUpperCase());
                statusCmb.setSelectedItem(currentStatus);
            } catch (IllegalArgumentException e) {
                statusCmb.setSelectedItem(EmployeeStatus.ACTIVE); // Default fallback
            }
        }
        
        // Populate and select email/role safely
        if (employeeToUpdate.getUser() != null) {
            emailTxt.setText(employeeToUpdate.getUser().getEmail());
    
        // FIX: Get the roles list and safely grab the first role
            java.util.List<String> userRoles = employeeToUpdate.getUser().getRoles();
            if (userRoles != null && !userRoles.isEmpty()) {
            String firstRole = userRoles.get(0); // Gets the first role in the list
            roleCmb.setSelectedItem(firstRole);
        }
        } else {
            emailTxt.setText("");
        }     
    }
    
    private void populateRolesDropdown() {
        roleCmb.removeAllItems(); // Clear default placeholders
    
        try {
            // Fetch the roles list directly from your DAO package
            DAO.EmployeeDAO dao = new DAO.EmployeeDAO();
            java.util.List<String> roles = dao.getRoleNames();
        
            for (String role : roles) {
                roleCmb.addItem(role);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Could not load database roles into UI: " + e.getMessage());
       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        departmentTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactNumTxt = new javax.swing.JTextField();
        roleCmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        statusCmb = new javax.swing.JComboBox<>();

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("[ Contact Number ]");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        updatePanel.setBackground(new java.awt.Color(51, 51, 51));

        updateBtn.setBackground(new java.awt.Color(0, 102, 255));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("[ Name: ]");

        nameTxt.setForeground(new java.awt.Color(0, 0, 0));
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("[ Department: ]");

        departmentTxt.setForeground(new java.awt.Color(0, 0, 0));
        departmentTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departmentTxtKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("[ Email ]");

        emailTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("[ Salary ]");

        salaryTxt.setForeground(new java.awt.Color(0, 0, 0));
        salaryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTxtKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("[ Contact Number ]");

        contactNumTxt.setForeground(new java.awt.Color(0, 0, 0));
        contactNumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNumTxtKeyTyped(evt);
            }
        });

        roleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleCmb.addActionListener(this::roleCmbActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("[ Role: ]");

        idTxt.setEditable(false);
        idTxt.setBackground(new java.awt.Color(102, 102, 102));
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.addActionListener(this::idTxtActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("[ ID: ]");

        cancelBtn.setBackground(new java.awt.Color(153, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update Employee");

        addressTxt.setForeground(new java.awt.Color(0, 0, 0));
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTxtKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("[ Address: ]");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Status");

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusCmb.addActionListener(this::statusCmbActionPerformed);

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)))
                .addGap(33, 33, 33))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactNumTxt)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(emailTxt)
                    .addComponent(jLabel8)
                    .addComponent(departmentTxt)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(nameTxt)
                    .addComponent(salaryTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(departmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCmb, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(cancelBtn))
                .addGap(70, 70, 70))
        );

        getContentPane().add(updatePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // 1. Clean data extracts
        String name = nameTxt.getText().trim();
        String address = addressTxt.getText().trim();
        String department = departmentTxt.getText().trim();
        String contactNum = contactNumTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String selectedRole = (String) roleCmb.getSelectedItem();
        EmployeeStatus selectedStatus = (EmployeeStatus) statusCmb.getSelectedItem();
        
        
        // 2. Validate standard structural fields
        if (name.isEmpty() || department.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, Department, and Email cannot be blank.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double salary;
        try {
            salary = Double.parseDouble(salaryTxt.getText().trim());
            if (salary <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be greater than zero.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please insert a valid numerical double format for salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Mutate fields directly onto the tracked reference model
        employeeToUpdate.setName(name);
        employeeToUpdate.setAddress(address.isEmpty() ? null : address);
        employeeToUpdate.setDepartment(department);
        employeeToUpdate.setContactNum(contactNum.isEmpty() ? null : contactNum);
        employeeToUpdate.setSalary(salary);
        
        if (selectedStatus != null) {
            employeeToUpdate.setStatus(selectedStatus.name()); 
        }
        // Mutate the inner User details
        if (employeeToUpdate.getUser() != null) {
            employeeToUpdate.getUser().setEmail(email);
        } else {
            // Safe fallback initialization if the nested user was null[cite: 1]
            User u = new User(employeeToUpdate.getUserId(), email, "PROTECTED", true);
            employeeToUpdate.setUser(u);
        }

        // 4. Submit updated data downward to the database service with the selected role[cite: 1]
        boolean isSuccess = service.modifyEmployee(employeeToUpdate, selectedRole);

        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Employee details successfully synchronized!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Refresh parent view display table if operational
            if (parentPanel != null) {
                parentPanel.loadTable();
            }
            this.dispose(); // Close modal window
        } else {
            JOptionPane.showMessageDialog(this, "Update routine database submission transaction rejected.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_updateBtnActionPerformed
    
    // Define your ComboBox with the Enum type
    
    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed

    }//GEN-LAST:event_idTxtActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
        char c = evt.getKeyChar();
    
    // Allow letters, spaces, hyphens, and apostrophes only
        if (!Character.isLetter(c) && c != ' ' && c != '-' && c != '\'') {
            evt.consume(); // Ignore the keystroke
        }
    }//GEN-LAST:event_nameTxtKeyTyped

    private void departmentTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departmentTxtKeyTyped
        char c = evt.getKeyChar();
    
    // Allow letters, spaces, hyphens, and apostrophes only
        if (!Character.isLetter(c) && c != ' ' && c != '-' && c != '\'') {
        evt.consume(); // Ignore the keystroke
        }
    }//GEN-LAST:event_departmentTxtKeyTyped

    private void salaryTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTxtKeyTyped
        char c = evt.getKeyChar();
    
        // Allow only digits and a dot
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Reject letter keys
        }
    
        // Prevent typing a second decimal point if one already exists
        if (c == '.' && salaryTxt.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_salaryTxtKeyTyped

    private void contactNumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumTxtKeyTyped
        char c = evt.getKeyChar();
    
        // Allow only digits and a '+' symbol at the start
        if (!Character.isDigit(c) && c != '+') {
            evt.consume(); // Reject letter keys
        }
    
        // Block '+' if it's not the very first character
        if (c == '+' && contactNumTxt.getText().length() > 0) {
            evt.consume(); 
        }
    }//GEN-LAST:event_contactNumTxtKeyTyped

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtKeyReleased

    private void addressTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtKeyTyped

    private void roleCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleCmbActionPerformed

    private void statusCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
        Employee dummyEmployee = new Model.Employee(); 
        dummyEmployee.setName("Test Employee");
        dummyEmployee.setDepartment("IT");
        dummyEmployee.setSalary(25000.0);
        
        // FIXED: Added "null" as the 4th argument (parentPanel) to match the constructor
        UpdateRecordDialog dialog = new UpdateRecordDialog(new javax.swing.JFrame(), true, dummyEmployee, null);
        
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField contactNumTxt;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> roleCmb;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JComboBox<String> statusCmb;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
