/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentation;

import DAO.DBConnection;
import Model.Employee;
import Model.User;
import Service.EmployeeService;
import Service.UserService;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer Ryzen 5
 */
public class UpdateRecordDialog extends javax.swing.JDialog {
    
    private Employee employeeToUpdate;
    private static final EmployeeService service = new EmployeeService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateRecordDialog.class.getName());

    /**
     * Creates new form UpdateRecordDialog
     */
    public UpdateRecordDialog(java.awt.Frame parent, boolean modal, Employee employee) {
       super(parent, modal);
       // 1. Initialize NetBeans UI elements first
    initComponents(); 
    
    // 2. Setup dropdown list data
    populateRolesDropdown();
    setTitle("Update Dialog");
    
    // 3. Bind the employee record and populate the form fields
    this.employeeToUpdate = employee;
    if (this.employeeToUpdate != null) {
        populateFormFields();
    }
    }
    
    
        private void populateFormFields() {
        // ID field stays read-only/uneditable 
        idTxt.setText(String.valueOf(employeeToUpdate.getUserId()));
        nameTxt.setText(employeeToUpdate.getName());
        departmentTxt.setText(employeeToUpdate.getDepartment());
        contactNumTxt.setText(employeeToUpdate.getContactNum() != null ? employeeToUpdate.getContactNum() : "");
        
        salaryTxt.setText(String.valueOf(employeeToUpdate.getSalary()));
        
    }
    
    private void populateRolesDropdown() {
        roleCmb.removeAllItems(); // Clear default placeholders
    
    // Explicitly query your database roles metadata
        String sql = "SELECT `name` FROM `roles`";
        try (
            Connection conn = DBConnection.GetConnection();
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            java.sql.ResultSet rs = stmt.executeQuery()
        ) {
            while (rs.next()) {
            roleCmb.addItem(rs.getString("name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Could not load database roles into UI: " + e.getMessage());
        // Fallback options in case database connection fails during startup
            roleCmb.addItem("Standard_Employee");
            roleCmb.addItem("HR_Admin");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        departmentTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactNumTxt = new javax.swing.JTextField();
        roleCmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("[ Contact Number ]");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        updatePanel.setBackground(new java.awt.Color(51, 51, 51));

        updateBtn.setBackground(new java.awt.Color(102, 102, 255));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("[ Name: ]");

        nameTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("[ Department: ]");

        departmentTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("[ Email ]");

        emailTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("[ Salary ]");

        salaryTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("[ Contact Number ]");

        contactNumTxt.setForeground(new java.awt.Color(0, 0, 0));

        roleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("[ Role: ]");

        idTxt.setEditable(false);
        idTxt.setBackground(new java.awt.Color(102, 102, 102));
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.addActionListener(this::idTxtActionPerformed);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("[ ID: ]");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactNumTxt)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(emailTxt)
                    .addComponent(jLabel8)
                    .addComponent(departmentTxt)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(nameTxt)
                    .addComponent(salaryTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGap(100, 100, 100))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        getContentPane().add(updatePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // 1. Clean data extracts
        String name = nameTxt.getText().trim();
        String department = departmentTxt.getText().trim();
        String contactNum = contactNumTxt.getText().trim();
        String email = emailTxt.getText().trim();
        String selectedRole = (String) roleCmb.getSelectedItem();

        // 2. Validate standard structural fields
        if (name.isEmpty() || department.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name, Department, and Email cannot be blank.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double salary;
        try {
            salary = Double.parseDouble(salaryTxt.getText().trim());
            if (salary <= 0) {
                JOptionPane.showMessageDialog(this, "Salary must be greater than zero.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please insert a valid numerical double format for salary.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Mutate fields directly onto the tracked reference model
        employeeToUpdate.setName(name);
        employeeToUpdate.setDepartment(department);
        employeeToUpdate.setContactNum(contactNum.isEmpty() ? null : contactNum);
        employeeToUpdate.setSalary(salary);
        
        // Mutate the inner User details
        if (employeeToUpdate.getUser() != null) {
            employeeToUpdate.getUser().setEmail(email);
        } else {
            // Safe fallback initialization if the nested user was null[cite: 1]
            User u = new User(employeeToUpdate.getUserId(), email, "PROTECTED", true);
            employeeToUpdate.setUser(u);
        }

        // 4. Submit updated data downward to the database service with the selected role[cite: 1]
        boolean isSuccess = service.modifyEmployee(employeeToUpdate, selectedRole);

        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Employee details successfully synchronized!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Close modal window
        } else {
            JOptionPane.showMessageDialog(this, "Update routine database submission transaction rejected.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed

    }//GEN-LAST:event_idTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Employee dummyEmployee = new Model.Employee(); 
        dummyEmployee.setName("Test Employee");
        dummyEmployee.setDepartment("IT");
        dummyEmployee.setSalary(25000.0);
                UpdateRecordDialog dialog = new UpdateRecordDialog(new javax.swing.JFrame(), true, dummyEmployee);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactNumTxt;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> roleCmb;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
