
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author BE214
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        evaluationBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        extraPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(102, 102, 102));
        sidePanel.setPreferredSize(new java.awt.Dimension(300, 400));

        employeeBtn.setBackground(new java.awt.Color(153, 153, 153));
        employeeBtn.setText("Employee Records");
        employeeBtn.setPreferredSize(new java.awt.Dimension(65, 22));
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(153, 153, 153));
        homeBtn.setText("Home");
        homeBtn.setMaximumSize(new java.awt.Dimension(172, 22));
        homeBtn.setMinimumSize(new java.awt.Dimension(172, 22));
        homeBtn.setPreferredSize(new java.awt.Dimension(90, 22));
        homeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                homeBtnMouseDragged(evt);
            }
        });
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        requestBtn.setBackground(new java.awt.Color(153, 153, 153));
        requestBtn.setText("Request");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        evaluationBtn.setBackground(new java.awt.Color(153, 153, 153));
        evaluationBtn.setText("Evaluation");
        evaluationBtn.setPreferredSize(new java.awt.Dimension(72, 22));
        evaluationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setText("Search");
        searchBtn.setMaximumSize(new java.awt.Dimension(172, 22));
        searchBtn.setMinimumSize(new java.awt.Dimension(172, 22));
        searchBtn.setPreferredSize(new java.awt.Dimension(90, 22));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(evaluationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addComponent(employeeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        add(sidePanel, java.awt.BorderLayout.WEST);

        mainPanel.setLayout(new java.awt.BorderLayout());

        extraPanel.setBackground(new java.awt.Color(102, 102, 102));
        extraPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(extraPanel, java.awt.BorderLayout.LINE_START);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        EmployeePanel panel2 = new EmployeePanel();

        mainPanel.removeAll();
        mainPanel.add(panel2);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        RequestPanel panel = new RequestPanel();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_requestBtnActionPerformed

    private void evaluationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationBtnActionPerformed
        EvaluationPanel panel = new EvaluationPanel();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_evaluationBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePanel2 panel = new HomePanel2();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SearchPanel panel = new SearchPanel();

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseDragged
        homeBtn.setBackground(Color.yellow);
    }//GEN-LAST:event_homeBtnMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton evaluationBtn;
    private javax.swing.JPanel extraPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    
}
