import javax.swing.JOptionPane;
import java.awt.Color;

public class MainFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JToggleButton();
        sidePanel = new javax.swing.JPanel();
        employeeBtn = new javax.swing.JToggleButton();
        reqBtn = new javax.swing.JToggleButton();
        searchBtn = new javax.swing.JToggleButton();
        addEvalBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        loginPanel.setBackground(new java.awt.Color(102, 102, 102));
        loginPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("CREWDECK");
        loginPanel.add(titleLabel);
        titleLabel.setBounds(80, 30, 121, 32);

        jLabel2.setText("Username:");
        loginPanel.add(jLabel2);
        jLabel2.setBounds(40, 80, 56, 16);

        Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username.setText("Admin");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        loginPanel.add(Username);
        Username.setBounds(44, 100, 180, 22);

        jLabel3.setText("Password:");
        loginPanel.add(jLabel3);
        jLabel3.setBounds(40, 140, 53, 16);

        Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        loginPanel.add(Password);
        Password.setBounds(44, 160, 180, 22);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(100, 210, 60, 22);

        sidePanel.setBackground(new java.awt.Color(0, 102, 102));
        sidePanel.setLayout(null);

        employeeBtn.setText("Employees");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(employeeBtn);
        employeeBtn.setBounds(40, 130, 110, 22);

        reqBtn.setText("Requests");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });
        sidePanel.add(reqBtn);
        reqBtn.setBounds(40, 170, 110, 22);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        sidePanel.add(searchBtn);
        searchBtn.setBounds(40, 90, 110, 22);

        addEvalBtn.setText("Add Evalutaion");
        addEvalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEvalBtnActionPerformed(evt);
            }
        });
        sidePanel.add(addEvalBtn);
        addEvalBtn.setBounds(40, 210, 110, 22);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String correctpass = "12345678";
        
        String username = Username.getText();
        char[] pass = Password.getPassword();
        
        
        if ( ( String.valueOf(pass).equals(correctpass))) 
        {
            JOptionPane.showMessageDialog(null,"Welcome: " + username); 
            
            HomePanel panel = new HomePanel();
            switchScreen(panel);
            
            getContentPane().removeAll();
            getContentPane().add(panel);
            getContentPane().revalidate();
            getContentPane().repaint();
            
        }
        
        else{
             JOptionPane.showMessageDialog(null, "Incorrect credentials");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        String correctpass = "12345678";
        
        String username = Username.getText();
        char[] pass = Password.getPassword();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) 
        {
            JOptionPane.showMessageDialog(null,"Welcome: " + username); 
            
            HomePanel panel = new HomePanel();
            switchScreen(panel);
            
            getContentPane().removeAll();
            getContentPane().add(panel);
            getContentPane().revalidate();
            getContentPane().repaint();
            
        }
        
        
        
    }//GEN-LAST:event_PasswordKeyPressed

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reqBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void addEvalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEvalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEvalBtnActionPerformed
    
    public void switchScreen(HomePanel newPanel){
        
        getContentPane().removeAll();
        getContentPane().add(newPanel);
        getContentPane().revalidate();
        getContentPane().repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JToggleButton addEvalBtn;
    private javax.swing.JToggleButton employeeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JToggleButton reqBtn;
    private javax.swing.JToggleButton searchBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
